# 1. NumPy N-dimensional Array

In [1]:
# create array
from numpy import array

lst = [1.0, 2.0, 3.0]
a = array(lst)

In [2]:
# display array
print(a)

[1. 2. 3.]


In [3]:
# display array dimention or shape

print(a.shape)

(3,)


In [4]:
# display array data type
print(a.dtype)

float64


# 2. Functions to Create Arrays

### Empty Function

In [5]:
# create empty array

from numpy import empty

a = empty([3,3])

print(a)

[[1.10872382e+219 4.92109139e+257 6.01334659e-154]
 [6.01347002e-154 1.71011789e+214 5.28555419e+180]
 [5.01390356e+180 1.69375270e+190 3.69028917e+180]]


### Zero Function

In [6]:
# create zero array

from numpy import zeros

a = zeros([3,5])

print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ones Function

In [7]:
# create one's array

from numpy import ones

a = ones([3,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# 3. Combining Arrays

#### Vertical Stack

In [8]:
# create array with vstack() function

from numpy import array
from numpy import vstack

# create first array
a1 = array([1,2,3])

# create second array
a2 = array([4,5,6])

In [10]:
print("The first array: ", a1)
print("The Second array: ",a2)

The first array:  [1 2 3]
The Second array:  [4 5 6]


In [11]:
# vertical stack of both the arrays

a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


#### Horizontal Stack

In [12]:
# create array with hstack() function

from numpy import array
from numpy import hstack

# create the first array
a1 = array([1, 2, 3])

# create the second array
a2 = array([4,5,6])

print("This is first array: ",a1)
print("This is second array: ",a2)

This is first array:  [1 2 3]
This is second array:  [4 5 6]


In [13]:
# create horizontal stack array

a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3 4 5 6]
(6,)
